#! /bin/bash
# load dependencies
. /u/local/Modules/default/init/modules.sh
#
module load intel/2020.4 
module load gcc/8.3.0
module load ncview/2.1.7
module load python/3.9.6
module load eigen/3.3.9 
module load nco/4.4.8
module load netcdf/f-4.8.1
module load pnetcdf/1.12.2 
module load cmake/3.30.0
module load wget/1.21
module load hdf5/1.12.0_gcc4.8.5-zlib
module load netcdf/c-4.7.4
# load virtual environment
source ~/.venv/canoe_py3.9.6/bin/activate
